apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mmam
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-mmam@sha256:37ef5d7f615e0f6ac313544c29b4a1fe15e388470e97578fd4cf0c55d503ceac
        name: my-nodejs
        resources: {}
status: {}
